### ISSUE TITLE
FEZMod crashes after "FEZ" screen

### ISSUE THREAD

**Issue by ghost** [AngelDE98/FEZMod#16] opened 2015-08-29 17:25 UTC
Hello,
When I launch FEZMod (from v2.0) and I type Gamepad A/Keyboard Enter, the game crashes with no error.
Note that I did the Windows 10 upgrade recently.
Do you know why it isn't working ?
Thank you !

**Comment by 0x0ade** [comment] 2015-08-29 17:28
Hi,

I can only guess you're running the Steam version. Could you try again with v0.3a1, which got silently released? I'm too lazy to write a changelog for that quite big patch, and the large amount of changes is also why it requires an alpha.

https://fezmod.tk/files/stable/FEZMOD_0.3a1.zip

EDIT: To clarify: The Steam version always had a special problem with FEZMod: Cloud saving. When I disabled it previously (with all Steamworks features, which means leaderboard, achievements, ...), I only used one flag. What I didn't know at that point is that there's a second flag responsible for the cloud saving. v0.3 (or a devbuild, but you need the new MonoMod.exe and mod.bat from v0.3) should fix it and v0.3a1 is the first alpha I've published for public testing.

**Comment by ghost** [comment] 2015-08-30 08:34
Thanks for replying !
But now I get a `System.IO.FileNotLoadException` (impossible to load the assembly `Mono.Cecil`).
I checked, `Mono.Cecil.dll` is already in the directory.

**Comment by 0x0ade** [comment] 2015-08-30 08:41
I've just created a new issue at the MonoMod repository. I recently changed the Mono.Cecil version required, but then changed it back.

https://github.com/AngelDE98/MonoMod/issues/2

I'll try to fix it ASAP (as soon as I turn on my PC, just woke up) and release v0.3a2

**Comment by ghost** [comment] 2015-08-30 08:45
Okay, thank you !

**Comment by 0x0ade** [comment] 2015-08-30 10:06
As expected, something messed up after I've changed the Mono.Cecil version back. MonoMod requires Mono.Cecil 0.9.5.0, while I've released v0.3a1 with... 0.9.6.0?! Also, I've been packing an "Debug" build as release, although I wanted to avoid that (performance problems).

(╯°□°）╯︵ ┻━┻

Bumped both to 0.9.6.0.

https://fezmod.tk/files/stable/FEZMOD_0.3a2.zip

**Comment by ghost** [comment] 2015-08-31 09:26
Okay, now the game (FEZMod 0.3a2) isn't starting...

http://paste.awesom.eu/thulemalta/vRUA

No window is opening.
I think it's a DLL problem, because when I verify game's integrity with Steam it replaces `Common.dll` and `FezEngine.dll`.
After that, the game crashes few seconds after launch...

http://paste.awesom.eu/thulemalta/eBEA

**Comment by 0x0ade** [comment] 2015-08-31 09:43
I've been able to get a first commit range causing this issue for
bisecting. I've planned to play multiplayer with someone with the exact
same issue. And as he deleted the speedrun mod and tried again, that one is
not faulty.

Now thanks to you I can further pinpoint the issue to either FezEngine.dll
or Common.dll. Could you try backing up Common.dll, patching v0.3a2 and
then using the backed-up Common.dll? (That means undoing FEZMod only for
Common.dll)

Alternatively I'm already working on v0.3a3, which should mainly help
debugging this issue, so you can just wait until I release a3.

ThuleMalta notifications@github.com schrieb am Mo., 31. Aug. 2015 11:26:

**Comment by ghost** [comment] 2015-08-31 10:50
FEZ doesn't launch even with the backed up `Common.dll`.

**Comment by 0x0ade** [comment] 2015-08-31 10:51
Someone on Twitter just pointed me at FezEngine.dll, but I can't find the issue.

FEZMod v0.3 - the broken update™

**Comment by 0x0ade** [comment] 2015-08-31 10:55
https://fezmod.tk/files/stable/FEZMOD_0.3a4.zip

**Comment by ghost** [comment] 2015-08-31 12:31
Not working too.
But now my antivirus says that FEZMod is a virus :p

**Comment by 0x0ade** [comment] 2015-08-31 12:33
O.o wow. What kind of virus at least and what file?

**Comment by ghost** [comment] 2015-08-31 12:39
I think it's a false positive.
I get a Win32 Evo-gen warning.
I don't know what file it is, because the antivirus warns me when I launch FEZMod and not before.

**Comment by 0x0ade** [comment] 2015-08-31 12:46
Yup, looks like a false-positive. https://steamcommunity.com/app/250640/discussions/0/611698195162519323/?insideModal=1

Has your warning also got the "[susp]" tag? If you want to be completely sure it's not a virus, feel free to compile MonoMod and FEZMod on your own. But I can only guess the "EMERGENCY" tag I embedded into a4 (not going to update the alpha version in the DLL until it works) caused it.

Could you "fix files" in Steam, extract v0.3a4 and then extract the v0.2 FezEngine.Mod.mm.dll on-top and then patch? I'm already on Windows and had to install Steam and FEZ and will try to replicate it (usually on Linux).

**Comment by ghost** [comment] 2015-08-31 13:18
Yes, I have the [susp] tag.

With v0.2 FezEngine.Mod.mm.dll, I have this error : 

```
Exception non gérée : System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à MonoMod.MonoMod.HasAttribute(MethodDefinition method, String attribute)
   à MonoMod.MonoMod.PatchRefsInMethod(MethodDefinition method)
   à MonoMod.MonoMod.PatchRefs(List`1 types)
   à MonoMod.MonoMod.AutoPatch()
   à MonoMod.MonoMod.Main(String[] args)
```

Edit:
After this error, it compiles properly.
At the end, I get the same thing that when Steam was replacing FEZMod files : the game becomes weird and then crashes.

Edit 2:
I disabled Steamworks with `-ns` tag and Steam Cloud on Steam settings, and I can now enjoy FEZMod 0.2 \o/ (alternative solution)

**Comment by 0x0ade** [comment] 2015-08-31 13:32
Now that I am finally able to replicate the issue, I'll set up a development environment on this Windows installation and debug / fix v0.3.

Back to the original issue: To get FEZMod v0.2 working in Steam, first "fix files" in Steam, then use this: https://fezmod.tk/files/stable/FEZMOD_0.2.zip and install it as usually. In Steam, set the following launch parameters:

-ns

If you still want to get achievements, use -sw instead.

Yup, that's it. It's just that v0.3 fixes this by default and I need testers, so... ¯\_(ツ)_/¯

**Comment by 0x0ade** [comment] 2015-08-31 14:06
Due to the progress gathered to the v0.3 issue, I'll simply rename this one and keep it open. If you want, feel free to unsubscribe at the right.

**Comment by 0x0ade** [comment] 2015-08-31 17:22
Testing manual find of the faulty devbuild, as bisecting this would be.. easier, I guess, but I'm on a limited disk-space Windows installation, so...

~~Conditions:~~
- ~~.mm.dlls refers to only FEZ.Mod.mm.dll and FezEngine.Mod.mm.dll, as Editor, Speedrun, etc. aren't faults.~~
- ~~MonoMod is always v0.3a4 as v0.2 .mm.dlls + v0.3a4 MonoMod patches and starts FEZ properly.~~
- ~~I guess this is some kind of poor-mans bisect~~

~~List:~~
- ~~100: Patches; crashes when finding the assembly FEZ.~~
- ~~80: Patches; crashes when finding the assembly FEZ.~~

**Comment by 0x0ade** [comment] 2015-08-31 19:34
I retried patching v0.2 with the v0.3a4 MonoMod. Although I was sure it was not the cause, it turns out a MonoMod change broke everything.

Closing this issue, renaming it to original; creating new issue at the MonoMod repository.

**Closed as completed by 0x0ade** 2015-08-31 19:34 UTC
